FROM python:3.10

RUN python3 -m pip install poetry==1.3.1

WORKDIR /app

ENV PATH="/app/.venv/bin:${PATH}"
ENV VIRTUAL_ENV="/app/.venv"

COPY poetry.lock poetry.toml pyproject.toml ./

RUN poetry install
